<a href="https://colab.research.google.com/github/BrianM50/MAT-422/blob/main/Section_1_2_(Elements_of_Linear_Algebra).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Elements of Linear Algebra**

In [ ]:
import numpy as np
import sympy as sympy
A = [1,2,3,4,5]
vectorA = np.array(A)
print('Row vector')
print(vectorA)
B = vectorA*2
print('Vector mulitplied by a scalar: ')
print(vectorA,"* 2 =",B)

Row vector
[1 2 3 4 5]
Vector mulitplied by a scalar: 
[1 2 3 4 5] * 2 = [ 2  4  6  8 10]


In [ ]:
print('In linear algebra a linear combination is a new vector constructed from a subset by multiplying each vector and adding the results.')
a = np.array([[1,2,3]])
b = np.array([[3,2,1]])
c = np.array([[2,1,3]])
print('a = ',a,'b = ', b,'c = ', c)
print('Linear Combination')
print('2a + 3b + 2c')
d = 2*a + 3*b +2*c
print(d)

In linear algebra a linear combination is a new vector constructed from a subset by multiplying each vector and adding the results.
a =  [[1 2 3]] b =  [[3 2 1]] c =  [[2 1 3]]
Linear Combination
2a + 3b + 2c
[[15 12 15]]


In [ ]:
print('A span is a set S of vectors which are the set of linear combinations of vectors in S.')
import numpy as np
e = np.array([[4,3]])
f = np.array([[1,2]])
print('e = ', e,  'f = ', f)
print('2e + 3f')
y = 2*e + 3*f
print(y)
print('The vectors e, f, and y are all part of the span, R^2.')

A span is a set S of vectors which are the set of linear combinations of vectors in S.
e =  [[4 3]] f =  [[1 2]]
2e + 3f
[[11 12]]
The vectors e, f, and y are all part of the span, R^2.


In [ ]:
print('Linear Independence occurs when a list of vectors cannot be written as a linear combinations of one another.')
g = np.array([4,5])
h = np.array([2,1])
print('g =', g, ' h =', h)
print('The vectors g and h are linearly independent because they are not multiples of each other (linear combinations).')

Linear Independence occurs when a list of vectors cannot be written as a linear combinations of one another.
g = [[4 5]]  h = [[2 1]]
The vectors g and h Are linearly independent because they are not multiples of each other (linear combinations).


In [ ]:
print('A list of vectors is linear dependent if it can be written as linear combination of the others.')
i = np.array([1,3])
j = np.array([3,6])
print('i =', i, ' j=',j)
print('Vectors i and j are linearly dependent because they are multiples of one another.')

A list of vectors is linear dependent if it can be written as linear combination of the others.
i = [[1 3]]  j= [[3 6]]
Vectors i and j are linearly dependent because they are multiples of one another.


In [ ]:
print('Orthogonality is when two vectors are perpendicular to each other. This can be computed by using a dot product. If the dot product equals zero the two vectors are perpendicular.')
k = np.array([-4,1])
l = np.array([1,4])
print('k =', k,' l =',l)
print('The dot product of k and l is zero.')
print('k*l =', np.dot(k,l))

Orthogonality is when two vectors are perpendicular to each other. This can be computed by using a dot product. If the dot product equals zero the two vectors are perpendicular.
k = [-4  1]  l = [1 4]
The dot product of k and l is zero.
k*l = 0


In [ ]:
print('The Gram-Schmidt process is used to convert linearly independent vectors into an orthogonal basis')
x1 = np.array([1,1,0])
x2 = np.array([-2,0,1])
print('Vectors x1 and x2 are linearly independent vectors')
print('x1 =',x1,' x2 =',x2)
v1 = x1/np.linalg.norm(x1)
v2 = x2 - ((np.dot(x2,x1))/np.dot(x1,x1))*x1
vo2 = v2/np.linalg.norm(v2)
print('We find the orthogonal basis to be')
print('v1 =',v1,' v2 =', vo2)

The Gram-Schmidt process is used to convert linearly independent vectors into an orthogonal basis
Vectors x1 and x2 are linearly independent vectors
x1 = [1 1 0]  x2 = [-2  0  1]
We find the orthogonal basis to be
v1 = [0.70710678 0.70710678 0.        ]  v2 = [-0.57735027  0.57735027  0.57735027]


In [ ]:
print('Eigenvalues and Eigenvectors can be computed using the equation Ax = λx, where A is an nxn matrix, λ is eigenvalue an of A, and x is a nx1 column vector, which is called an eigenvector.')
import numpy as np
from numpy.linalg import eig
import scipy.linalg as la
mA = np.array([[2,1],[-1,0]])
print('Matrix A:')
print(mA)
eigvals, eigvecs = la.eig(mA)
v1 = eigvecs[:,1].reshape(2,1)
print('Eigenvalues = ', eigvals.real)
print('Eigenvector =')
print(v1)

Eigenvalues and Eigenvectors can be computed using the equation Ax = λx, where A is an nxn matrix, λ is eigenvalue of A, and x is nx1 column vector, which is a called an eigenvector
Matrix A:
[[ 2  1]
 [-1  0]]
Eigenvalues =  [1. 1.]
Eigenvector =
[[-0.70710678]
 [ 0.70710678]]
