<a href="https://colab.research.google.com/github/BrianM50/MAT-422/blob/main/Section_1_3(Linear_Regression).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Linear** **Regression**

In [49]:
print("QR decomposition is used to solve the linear least squares problem. Using the Gram-Schmidt process we break down Matrix so that A = QR, where Q is an orthnormal matrix and R is an upper triangular matrix R.")
import numpy as np
A = np.array([[20,15,30],[15,50,48],[5,24,6]], dtype = float)
print("Matrix A")
print(A)
x1 = np.array([20,15,5])
x2 = np.array([15,50,24])
x3 = np.array([30,48,6])
print('x1 =',x1,' x2 =', x2,' x3 =', x3)
v1 = x1/np.linalg.norm(x1)
v2 = x2 - ((np.dot(x2,x1))/np.dot(x1,x1))*x1
vo2 = v2/np.linalg.norm(v2)
v3 = x3 - (((np.dot(x3,x1))/np.dot(x1,x1))*x1) - (((np.dot(x3,v2))/np.dot(v2,v2))*v2)
vo3 = v3/np.linalg.norm(v3)
print('')
print('We find the orthnormal basis to be')
print('v1 =', v1, ' v2 =', vo2,' v3 =', vo3)
print('')
print('The Matrix Q will then be')
Qtranspose = np.array([[v1],[vo2],[vo3]])
Q = Qtranspose.transpose()
print(Q)
print('')
print('To find R we need to multiply the transpose of Q by A, Q^(T)A = R')
r = np.dot(Qtranspose, A)
R = np.rint(r)
print('R =')
print(R)

QR decomposition is used to solve the linear least squares problem. Using the Gram-Schmidt process we break down Matrix so that A = QR, where Q is an orthnormal matrix and R is an upper triangular matrix R.
Matrix A
[[20. 15. 30.]
 [15. 50. 48.]
 [ 5. 24.  6.]]
x1 = [20 15  5]  x2 = [15 50 24]  x3 = [30 48  6]

We find the orthnormal basis to be
v1 = [0.78446454 0.58834841 0.19611614]  v2 = [-0.6074847   0.66534038  0.43391764]  v3 = [-0.12481077  0.45953055 -0.87934859]

The Matrix Q will then be
[[[ 0.78446454 -0.6074847  -0.12481077]]

 [[ 0.58834841  0.66534038  0.45953055]]

 [[ 0.19611614  0.43391764 -0.87934859]]]

To find R we need to multiply the transpose of Q by A, Q^(T)A = R
R =
[[[25. 46. 53.]]

 [[ 0. 35. 16.]]

 [[-0. -0. 13.]]]


In [6]:
print('The least-squares problems involves solving for the system Ax = b, where A is a nxm matrix. Since matrix A is not a square matrix we have to use QR decomposition to solve the system')
print('Ax = b')
print('QRx = b')
print('Rx = Q^(T)b')
print('x = R^(-1)Q^(T)b')
import numpy as np
import math
B = np.array([[0,1],[1, 3],[2, 1]], dtype = float)
print('')
print("Matrix A")
print(B)
y1 = np.array([0,1,2])
y2 = np.array([1,3,1])
print('y1 =',y1,' y2 =', y2)
print('')
ve1 = y1/np.linalg.norm(y1)
ve2 = y2 - ((np.dot(y2,y1))/np.dot(y1,y1))*y1
vec2 = ve2/np.linalg.norm(ve2)
print('We find the orthnormal basis to be')
print('v1 =', ve1, ' v2 =', vec2)
Q = np.array([[0,(math.sqrt(6))/6],[(math.sqrt(5))/5,(math.sqrt(6))/3],[2*(math.sqrt(5))/5,-(math.sqrt(6))/6]])
print('')
print('The Matrix Q is')
print(Q)

print('')
R = np.dot(Q.transpose(),B)
print('The R matrix is')
print(np.rint(R))

print('')
print('Let vector b be')
b = np.array([[1],[5],[6]], dtype = float)
print(b)
print('')
print('Now that we have the matices Q and R we can solve for x using the system QRx = b')
Qt = Q.transpose()
Rinv = np.linalg.inv(R)
print('Q^(T) =')
print(Qt)
print('')
print('R^(-1) =')
print(Rinv)
print('')
Qb = np.dot(Qt,b)
x = np.dot(Rinv, Qb)
print('Plugging these matrices into the equation x = R^(-1)Q^(T)b, we get x =')
print(x)
print('')
print('To check this is the correct x we multiply the matrix A by x to get b, Ax = b')
vecb = np.dot(B,x)
print(np.rint(vecb))

The least-squares problems involves solving for the system Ax = b, where A is a nxm matrix. Since matrix A is not a square matrix we have to use QR decomposition to solve the system
Ax = b
QRx = b
Rx = Q^(T)b
x = R^(-1)Q^(T)b

Matrix A
[[0. 1.]
 [1. 3.]
 [2. 1.]]
y1 = [0 1 2]  y2 = [1 3 1]

We find the orthnormal basis to be
v1 = [0.         0.4472136  0.89442719]  v2 = [ 0.40824829  0.81649658 -0.40824829]

The Matrix Q is
[[ 0.          0.40824829]
 [ 0.4472136   0.81649658]
 [ 0.89442719 -0.40824829]]

The R matrix is
[[2. 2.]
 [0. 2.]]

Let vector b be
[[1.]
 [5.]
 [6.]]

Now that we have the matices Q and R we can solve for x using the system QRx = b
Q^(T) =
[[ 0.          0.4472136   0.89442719]
 [ 0.40824829  0.81649658 -0.40824829]]

R^(-1) =
[[ 0.4472136  -0.40824829]
 [ 0.          0.40824829]]

Plugging these matrices into the equation x = R^(-1)Q^(T)b, we get x =
[[2.56666667]
 [0.83333333]]

To check this is the correct x we multiply the matrix A by x to get b, Ax = b
[[1.